- id: bedroom-closet-opened-closed
  alias: "Bedroom Closet Opened/Closed"
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id:
        - sensor.bedroom_closet_door
      to: 'open'
    - platform: state
      entity_id:
        - sensor.bedroom_closet_door
      to: 'closed'
  action:
    - data:
        entity_id:
          - light.bedroom_closet_light
      service_template: "light.turn_{% if (trigger.to_state.state == 'open') %}on{% elif (trigger.to_state.state == 'closed') %}off{% endif %}"

- id: bathroom-motion-detected
  alias: "Bathroom Motion Detected"
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id:
        - sensor.master_bathroom_motion_detected
      to: 'yes'
    - platform: state
      entity_id:
        - sensor.guest_bathroom_motion_detected
      to: 'yes'
  action:
    - data_template:
        entity_id:
          - "light.{{ trigger.entity_id.split('.')[1].split('_')[0] }}_bathroom_vanity_light"
          - "light.{{ trigger.entity_id.split('.')[1].split('_')[0] }}_bathroom_light"
      service: light.turn_on

- id: bathroom-motion-stopped
  alias: "Bathroom Motion Stopped"
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id:
        - sensor.master_bathroom_motion_detected
      to: 'no'
      for: '00:05:00'
    - platform: state
      entity_id:
        - sensor.guest_bathroom_motion_detected
      to: 'no'
      for: '00:07:00'
  action:
    - data_template:
        entity_id:
          - "light.{{ trigger.entity_id.split('.')[1].split('_')[0] }}_bathroom_vanity_light"
          - "light.{{ trigger.entity_id.split('.')[1].split('_')[0] }}_bathroom_light"
      service: light.turn_off

- id: bathroom-switch-off
  alias: "Bathroom Switch Off"
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id:
        - light.guest_bathroom_light
      to: 'off'
    - platform: state
      entity_id:
        - light.guest_bathroom_vanity_light
      to: 'off'
    - platform: state
      entity_id:
        - light.master_bathroom_light
      to: 'off'
    - platform: state
      entity_id:
        - light.master_bathroom_vanity_light
      to: 'off'
  action:
    - data_template:
        entity_id:
          - "light.{{ trigger.entity_id.split('.')[1].split('_')[0] }}_bathroom_light"
          - "light.{{ trigger.entity_id.split('.')[1].split('_')[0] }}_bathroom_vanity_light"
      service: light.turn_off

- id: google-type
  alias: "Google Type"
  initial_state: 'on'
  trigger:
    - platform: event
      event_type: ifttt_webhook_received
      event_data:
        action: call_service
  action:
    - service: script.tv_character_keypress
      data_template:
        character: '{{ trigger.event.data.text }}'
