- id: bedroom-closet-opened-closed
  alias: "Bedroom Closet Opened/Closed"
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id:
        - sensor.bedroom_closet_door
      to: 'open'
    - platform: state
      entity_id:
        - sensor.bedroom_closet_door
      to: 'closed'
  action:
    - data:
        entity_id:
          - switch.bedroom_closet_light
      service_template: "switch.turn_{% if (trigger.to_state.state == 'open') %}on{% elif (trigger.to_state.state == 'closed') %}off{% endif %}"

- id: bathroom-motion-detected
  alias: "Bathroom Motion Detected"
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id:
        - sensor.bathroom_motion_detected
      to: 'yes'
  action:
    - data:
        entity_id:
          - switch.bathroom_vanity_light
          - switch.bathroom_light
      service: switch.turn_on

- id: bathroom-motion-stopped
  alias: "Bathroom Motion Stopped"
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id:
        - sensor.bathroom_motion_detected
      to: 'no'
      for: '00:05:00'
  action:
    - data:
        entity_id:
          - switch.bathroom_vanity_light
          - switch.bathroom_light
      service: switch.turn_off
