- id: closet-opened-closed
  alias: "Closet Opened/Closed"
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.bedroom_closet_door
      to: 'on'
    - platform: state
      entity_id:
        - binary_sensor.bedroom_closet_door
      to: 'off'
    - platform: state
      entity_id:
        - binary_sensor.office_closet_door
      to: 'on'
    - platform: state
      entity_id:
        - binary_sensor.office_closet_door
      to: 'off'
  action:
    - data_template:
        entity_id:
          - "light.{{ trigger.entity_id.split('.')[1].split('_')[0] }}_closet_light"
      service_template: "light.turn_{{ trigger.to_state.state }}"

- id: front-door-opened
  alias: "Front Door Opened"
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.front_door
      to: 'on'
  action:
    - data:
        entity_id:
          - light.foyer_light
      service: light.turn_on
- id: turn-off-foyer
  alias: "Turn Off Foyer"
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.front_door
      to: 'off'
      for:
        minutes: 3
  action:
    - data:
        entity_id:
          - light.foyer_light
      service: light.turn_off

- id: bathroom-motion-detected
  alias: "Bathroom Motion Detected"
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id:
        - sensor.master_bathroom_motion_detected
      to: 'yes'
    - platform: state
      entity_id:
        - sensor.guest_bathroom_motion_detected
      to: 'yes'
  action:
    - data_template:
        entity_id:
          - "light.{{ trigger.entity_id.split('.')[1].split('_')[0] }}_bathroom_vanity_light"
          - "light.{{ trigger.entity_id.split('.')[1].split('_')[0] }}_bathroom_light"
      service: light.turn_on

- id: bathroom-motion-stopped
  alias: "Bathroom Motion Stopped"
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id:
        - sensor.master_bathroom_motion_detected
      to: 'no'
      for: '00:05:00'
    - platform: state
      entity_id:
        - sensor.guest_bathroom_motion_detected
      to: 'no'
      for: '00:07:00'
  action:
    - data_template:
        entity_id:
          - "light.{{ trigger.entity_id.split('.')[1].split('_')[0] }}_bathroom_vanity_light"
          - "light.{{ trigger.entity_id.split('.')[1].split('_')[0] }}_bathroom_light"
      service: light.turn_off

- id: bathroom-switch-off
  alias: "Bathroom Switch Off"
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id:
        - switch.guest_bathroom_light
      to: 'off'
    - platform: state
      entity_id:
        - switch.guest_bathroom_vanity_light
      to: 'off'
    - platform: state
      entity_id:
        - switch.master_bathroom_light
      to: 'off'
    - platform: state
      entity_id:
        - switch.master_bathroom_vanity_light
      to: 'off'
  action:
    - data_template:
        entity_id:
          - "light.{{ trigger.entity_id.split('.')[1].split('_')[0] }}_bathroom_light"
          - "light.{{ trigger.entity_id.split('.')[1].split('_')[0] }}_bathroom_vanity_light"
      service: light.turn_off

- id: google-type
  alias: "Google Type"
  initial_state: 'on'
  trigger:
    - platform: event
      event_type: ifttt_webhook_received
      event_data:
        action: call_service
  action:
    - service: script.tv_character_keypress
      data_template:
        character: '{{ trigger.event.data.text }}'
