- id: bathroom-light-motion
  alias: "Bathroom Light Motion"
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id:
        - sensor.bathroom_motion
      to: '8'
  action:
    - service: switch.turn_on
      data:
        entity_id:
          - switch.vanity
          - switch.bathroom
 - id: bathroom-light-motion-stopped
   alias: "Bathroom Light Motion Stopped"
   initial_state: 'on'
   trigger:
     - platform: state
       entity_id:
         - sensor.bathroom_motion
       to: '0'
       for:
         minutes: 3
   condition:
     - condition: state
       entity_id: sensor.bathroom_humidity
       below: 52.0
   action:
     - service: switch.turn_off
       data:
         entity_id:
           - switch.vanity
           - switch.bathroom
