- id: bedroom-closet-opened-closed
  alias: "Bedroom Closet Opened/Closed"
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id:
        - sensor.bedroom_closet_door
      to: 'open'
    - platform: state
      entity_id:
        - sensor.bedroom_closet_door
      to: 'closed'
  action:
    - service_template: >
        switch.turn_{{ if trigger.to_state.state == 'open' }}on{{ elif trigger.to_state.state == 'closed' }}off{{ endif }}
      data:
        entity_id:
          - switch.bedroom_closet_light

- id: bathroom-light-motion
  alias: "Bathroom Light Motion"
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id:
        - sensor.bathroom_motion
      to: '8'
  action:
    - service: switch.turn_on
      data:
        entity_id:
          - switch.vanity
          - switch.bathroom
- id: bathroom-light-motion-stopped
  alias: "Bathroom Light Motion Stopped"
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id:
        - sensor.bathroom_motion
      to: '0'
      for:
        minutes: 3
  condition:
    - condition: numeric_state
      entity_id: sensor.bathroom_humidity
      below: 58
  action:
    - service: switch.turn_off
      data:
        entity_id:
          - switch.vanity
          - switch.bathroom
