- platform: template
  sensors:
    bedroom_closet_door:
      friendly_name: "Bedroom Closet Door"
      value_template: >-
        {% if is_state('sensor.bedroom_closet_sensor_state', '22') %}
          on
        {% else %}
          off
        {% endif %}
