homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 0
  unit_system: imperial
  time_zone: !secret timezone
  customize: !include customize.yaml
default_config:
#introduction:
#http:
#  base_url: example.duckdns.org:8123
discovery:
sensor: !include sensors.yaml
tts:
  - platform: google
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
switch: !include switches.yaml
cloud: !include cloud.yaml
history:
zwave: !include zwave.yaml
