- platform: statistics
  entity_id: sensor.bathroom_humidity
  name: Bathroom Humidity
  sampling_size: 400
  max_age:
    minutes: 300
- platform: template
  sensors:
    bedroom_closet_door:
      friendly_name: "Bedroom Closet Door"
      value_template: >-
        {% if is_state('sensor.bedroom_closet_sensor_state', '22') %}
          open
        {% elif is_state('sensor.bedroom_closet_sensor_state', '23') %}
          closed
        {% else %}
          unknown
        {% endif %}
      icon_template: >-
        {% if is_state('sensor.bedroom_closet_sensor_state', '22') %}
          mdi:door-open
        {% elif is_state('sensor.bedroom_closet_sensor_state', '23') %}
          mdi:door-closed
        {% else %}
          mdi:alert
        {% endif %}
