- platform: statistics
  entity_id: sensor.bathroom_humidity
  name: Bathroom Humidity
  sampling_size: 400
  max_age:
    minutes: 300
- platform: template
  sensors:
    bedroom_closet_door:
      friendly_name: "Bedroom Closet Door"
      value_template: >-
        {% if is_state('sensor.bedroom_closet_sensor_state', '22') %}
          open
        {% elif is_state('sensor.bedroom_closet_sensor_state', '23') %}
          closed
        {% else %}
          unknown
        {% endif %}
      icon_template: >-
        {% if is_state('sensor.bedroom_closet_sensor_state', '22') %}
          mdi:door-open
        {% elif is_state('sensor.bedroom_closet_sensor_state', '23') %}
          mdi:door-closed
        {% else %}
          mdi:alert
        {% endif %}
    bathroom_motion_sensor:
      friendly_name: "Bathroom motion sensor"
      value_template: >-
        {% if is_state('sensor.bathroom_vanity_light_sensor_state', '8') %}
          true
        {% elif is_state('sensor.bathroom_vanity_light_sensor_state', '0') %}
          false
        {% else %}
          null
        {% endif %}
      icon_template: >-
        {% if is_state('sensor.bathroom_vanity_light_sensor_state', '8') %}
          mdi:exit-run
        {% elif is_state('sensor.bathroom_vanity_light_sensor_state', '0') %}
          mdi:door
        {% else %}
          mdi:alert
        {% endif %}
    guest_bathroom_motion_sensor:
      friendly_name: "Bathroom motion sensor"
      value_template: >-
        {% if is_state('sensor.guest_bathroom_vanity_light_sensor_state', '8') %}
          true
        {% elif is_state('sensor.guest_bathroom_vanity_light_sensor_state', '0') %}
          false
        {% else %}
          null
        {% endif %}
      icon_template: >-
        {% if is_state('sensor.guest_bathroom_vanity_light_sensor_state', '8') %}
          mdi:exit-run
        {% elif is_state('sensor.guest_bathroom_vanity_light_sensor_state', '0') %}
          mdi:door
        {% else %}
          mdi:alert
        {% endif %}
