- platform: command_line
  switches:
    bedroom_tv:
      friendly_name: 'Bedroom TV'
      command_on: 'curl -X POST http://{{ states('sensor.bedroomroom_tv_ip') }}:8060/keypress/PowerOn'
      command_off: 'curl -X POST http://192.168.50.62:8060/keypress/PowerOff'
      command_state: 'curl -s GET http://192.168.50.62:8060/query/device-info | grep power-mode | sed -e "s:<power-mode>DisplayOff</power-mode>:OFF:" -e "s:<power-mode>PowerOn</power-mode>:ON:"'
      value_template: '{{ value == "ON" }}'
    living_room_tv:
      friendly_name: 'Living Room TV'
      command_on: 'curl -X POST http://{{ states('sensor.living_room_tv_ip') }}:8060/keypress/PowerOn'
      command_off: 'curl -X POST http://{{ states('sensor.living_room_tv_ip') }}:8060/keypress/PowerOff'
      command_state: 'curl -s GET http://{{ states('sensor.living_room_tv_ip') }}:8060/query/device-info | grep power-mode | sed -e "s:<power-mode>DisplayOff</power-mode>:OFF:" -e "s:<power-mode>PowerOn</power-mode>:ON:"'
      value_template: '{{ value == "ON" }}'
- platform: template
  switches:
    bedroom_tv:
      value_template: '{{ states('sensor.bedroom_tv_state') }}'
      turn_on:
        service: script.tv_keypress
        data_template:
          key: "PowerOn"
          ip: '{{ states("sensor.bedroom_tv_ip") }}'
      turn_off:
        service: script.tv_keypress
        data_template:
          key: "PowerOff"
          ip: '{{ states("sensor.bedroom_tv_ip") }}'

- platform: template
  switches:
    living_room_tv:
      value_template: '{{ states('sensor.living_room_tv_state') }}'
      turn_on:
        service: script.tv_keypress
        data_template:
          key: "PowerOn"
          ip: '{{ states("sensor.living_room_tv_ip") }}'
      turn_off:
        service: script.tv_keypress
        data_template:
          key: "PowerOff"
          ip: '{{ states("sensor.living_room_tv_ip") }}'
