- platform: template
  switches:
    bedroom_tv:
      friendly_name: Bedroom TV
      value_template: '{{ states("sensor.bedroom_tv_state") }}'
      turn_on:
        service: script.tv_keypress
        data_template:
          key: "PowerOn"
          ip: '{{ states("sensor.bedroom_tv_ip") }}'
      turn_off:
        service: script.tv_keypress
        data_template:
          key: "PowerOff"
          ip: '{{ states("sensor.bedroom_tv_ip") }}'
    living_room_tv:
      friendly_name: Living Room TV
      value_template: '{{ states("sensor.living_room_tv_state") }}'
      turn_on:
        service: script.tv_keypress
        data_template:
          key: "PowerOn"
          ip: '{{ states("sensor.living_room_tv_ip") }}'
      turn_off:
        service: script.tv_keypress
        data_template:
          key: "PowerOff"
          ip: '{{ states("sensor.living_room_tv_ip") }}'
